services:
  # nuxt:
  #   build: ./frontend
  #   container_name: nuxt-app
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   environment:
  #     - API_URL=${API_URL}
  #   env_file:
  #     - .env

  bot:
    build: ../burlang-
    container_name: telegram-bot
    restart: always
    environment:
      - API_URL=http://express-api:5000
      - BOT_TOKEN=${BOT_TOKEN}
    ports: 
      - "1337:1337"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - burlive

  api:
    build: ./api
    container_name: express-api
    restart: always
    environment:
      - MONGO_URL=${MONGO_URL}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - burlive

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf:ro
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: mongod --config /etc/mongo/mongod.conf
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - BURLIVE_DB_USER=${BURLIVE_DB_USER}
      - BURLIVE_DB_PASSWORD=${BURLIVE_DB_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - burlive

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - nuxt
  #     - api

networks:
  burlive:
    external: true

volumes:
  mongo_data:
