name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH Connection
        run: |
          ssh deployer@195.133.31.15 'echo "SSH connection successful"'

      - name: Deploy to VPS via SSH
        run: |
          ssh deployer@195.133.31.15 '
            cd /home/burlive &&
            git pull &&
            docker compose down &&
            docker compose up -d --build
          '
