name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 195.133.31.15 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh deployer@195.133.31.15 'echo "SSH connection successful"'

      - name: Deploy to VPS via SSH
        run: |
          ssh deployer@195.133.31.15 '
            cd /home/burlive &&
            git pull &&
            docker compose down &&
            docker compose up -d --build
          '
