name: Node.js CI/CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Kill existing process on port 5000
        run: |
          sudo lsof -t -i:5000 | xargs -I{} sudo kill -9 {}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: compile
        run: npm install

      - name: compile
        run: npx tsc --p tsconfig.json

      - name: run
        run: node dist