name: Node.js CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Update code on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            lsof -i :5000 | awk 'NR!=1 {print $2}' | xargs kill -9
            cd /opt/burlive
            git restore .
            git pull
            npx tsc -p tsconfig.json
            nohup node dist/index.js > output.log 2>&1 & disown
