name: Node.js CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Stop port 5000
        run: |
          #!/bin/bash
          kill $(lsof -t -i :5000)
        shell: bash

      - name: Update code on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/burlive
            git pull
            npx tsc -p tsconfig.json
            node dist/index.js &
